// apps/react/src/app/stages/posts-stage/posts-stage.tsx
import React from 'react';

import './posts-stage.css';
import Posts from '../../components/posts/posts';
import NextStageButton from '../../components/next-stage-button/next-stage-button';
import { Post } from '@rxjs-tutorial/data';
import { of } from 'rxjs';
import { posts } from '@rxjs-tutorial/solutions';

/* tslint:disable:no-empty-interface */
export interface PostsStageProps {}
export interface PostsStageState {
  posts?: Post[];
  src: string;
}

export class PostsStage extends React.Component<
  PostsStageProps,
  PostsStageState
> {
  constructor(props: PostsStageProps) {
    super(props);
    this.state = { src: 'https://jsonplaceholder.typicode.com/posts' };
  }
  componentDidMount() {
    // Prepare http request to get posts
    // use it as an Observable
    // Solution:
    // const source$ = posts(this.state.src)

    const source$ = of([]);
    source$.subscribe((posts: Post[]) => {
      this.setState({ posts });
    });
  }
  render() {
    return (
      <div className="posts-stage__container">
        <h5>Source component: apps/react/src/app/stages/posts-stage</h5>
        <h2>
          Load and display posts from{' '}
          <a href={this.state.src}>{this.state.src}</a>
        </h2>
        <NextStageButton stage={4} />
        <Posts posts={this.state.posts} />
      </div>
    );
  }
}

export default PostsStage;

// apps/ng/src/app/stages/posts-stage/posts.stage.component.ts
import { Component, OnInit } from '@angular/core';
import { Post } from '@rxjs-tutorial/data';
import { posts } from '@rxjs-tutorial/solutions';
import { of } from 'rxjs';

@Component({
  selector: 'rxjs-tutorial-posts-stage',
  templateUrl: './posts.stage.component.html',
  styleUrls: ['./posts.stage.component.css']
})
export class PostsStageComponent implements OnInit {
  posts: Post[];
  readonly src = 'https://jsonplaceholder.typicode.com/posts';
  constructor() {}

  ngOnInit() {
    // Prepare http request to get posts
    // use it as an Observable
    // Solution:
    // const source$ = posts(this.http, this.src)

    const source$ =  of([]);
    source$.subscribe((posts: Post[]) => {
      this.posts = posts;
    });
  }
}

<div class="posts-stage__container">
  <h5>Source component: apps/ng/src/app/stages/posts-stage</h5>
  <h2>
    Load and display posts from
    <a [href]="src">{{ src }}</a>
  </h2>
  <rxjs-tutorial-next-stage-button
    [stage]="4"
  ></rxjs-tutorial-next-stage-button>
  <rxjs-tutorial-posts *ngIf="posts" [posts]="posts"> </rxjs-tutorial-posts>
</div>
