// apps/ng/src/app/components/post/post.component.ts
import { Component, OnInit, Input } from '@angular/core';
import { Post } from '@rxjs-tutorial/data';

@Component({
  selector: 'rxjs-tutorial-post',
  templateUrl: './post.component.html',
  styleUrls: ['./post.component.css']
})
export class PostComponent implements OnInit {

  @Input()
  post: Post;
  constructor() { }

  ngOnInit() {
  }

}

<div class="container">
  <mat-card>
    <h2>{{ post.title }}</h2>
    <p>{{ post.body }}</p>
    <mat-expansion-panel *ngIf="post.comments">
      <mat-expansion-panel-header>
        <mat-panel-title>
          Comments
        </mat-panel-title>
      </mat-expansion-panel-header>
      <ol>
      <li *ngFor="let comment of post.comments">
        {{ comment.body }}
      </li>
    </ol>
    </mat-expansion-panel>
  </mat-card>
</div>

// apps/react/src/app/components/post/post.tsx
import React from 'react';

import './post.css';
import {
  Card,
  CardContent,
  ExpansionPanel,
  ExpansionPanelSummary,
  ExpansionPanelDetails
} from '@material-ui/core';
import { Post as PostI, Comment } from '@rxjs-tutorial/data';

/* tslint:disable:no-empty-interface */
export interface PostProps {
  post: PostI;
}

export const Post = (props: PostProps) => {
  const comments: JSX.Element = props.post.comments ? (
    <ol>
      {props.post.comments.map((comment: Comment) => {
        return <li>{comment.body}</li>;
      })}
    </ol>
  ) : null;
  return (
    <div className="container">
      <Card>
        <CardContent>
          <h2>{props.post.title}</h2>
          <p>{props.post.body}</p>
          <ExpansionPanel>
            <ExpansionPanelSummary>Comments</ExpansionPanelSummary>
            <ExpansionPanelDetails>{comments}</ExpansionPanelDetails>
          </ExpansionPanel>
        </CardContent>
      </Card>
    </div>
  );
};

export default Post;
